admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

admin_app_question_accept:
    path: /admin/app/question/{id}/accept
    controller: App\Controller\Admin\QuestionAcceptController
    methods: [GET]
