apiVersion: 1

datasources:
    - name: MySQL
      type: mysql
      url: mysql:3306
      database: questions
      user: user
      secureJsonData:
          password: password
      isDefault: true
      editable: true
